services:
  mongo:
    image: mongo:6.0
    container_name: confectionery-mongo
    ports: ['27017:27017']
    volumes: ['mongo-data:/data/db']
  auth:
    build: ./auth-service
    container_name: confectionery-auth
    ports: ['8001:8000']
    environment: { MONGO: mongodb://mongo:27017, SECRET: your_jwt_secret }
    depends_on: ['mongo']
  catalog:
    build: ./catalog-service
    container_name: confectionery-catalog
    ports: ['8002:8000']
    environment: { MONGO: mongodb://mongo:27017 }
    depends_on: ['mongo']
  order:
    build: ./order-service
    container_name: confectionery-order
    ports: ['8003:8000']
    environment: { MONGO: mongodb://mongo:27017, AUTH_URL: http://auth:8000, CATALOG_URL: http://catalog:8000 }
    depends_on: ['auth','catalog','mongo']
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: confectionery-frontend
    ports: ['3001:3000']
    depends_on: ['auth','catalog','order']
volumes:
  mongo-data:
